// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenThiQuynhTrang0611.Data;

#nullable disable

namespace NguyenThiQuynhTrang0611.Migrations
{
    [DbContext(typeof(NTQTDb))]
    [Migration("20230104013427_Create_Table_Company")]
    partial class CreateTableCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("NguyenThiQuynhTrang0611.Models.CompanyNTQT0611", b =>
                {
                    b.Property<string>("CompanyID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyID");

                    b.ToTable("CompanyNTQT0611s");
                });
#pragma warning restore 612, 618
        }
    }
}
